# version: '3.9'
services:
  api:
    build:
      context: ./saleor-api/
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    # env_file:
    #   - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      jaeger:
        condition: service_started
    volumes:
      - saleor-media:/app/media
    environment:
      RSA_PRIVATE_KEY: ${RSA_PRIVATE_KEY}
      GRAPHQL_API_URL: ${GRAPHQL_API_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_GRAPHQL_ORIGINS: "${DASHBOARD_URL},${API_URL}"
      API_URL: ${API_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      JAEGER_AGENT_HOST: ${JAEGER_AGENT_HOST}
      DASHBOARD_URL: ${DASHBOARD_URL}
      DATABASE_URL: ${DATABASE_URL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", "-X", "POST", "http://localhost:8000/graphql/", "--data", "{\"query\":\"{__typename}\"}", "-H", "Content-Type: application/json"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - saleor-backend-tier

  dashboard:
    build:
      context: ./saleor-dashboard/
      dockerfile: Dockerfile
    ports: 
      - "9000:80"
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://dashboard:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    networks:
      - saleor-backend-tier

  db:
    image: postgres:15-alpine   
    ports:
     - "5432:5432"
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "saleor"]
      interval: 10s
      retries: 5
      start_period: 10s
    
    networks:
      - saleor-backend-tier

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - saleor-redis:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
 
    networks:
    - saleor-backend-tier
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "6831:6831/udp"
    volumes: 
      - /tmp
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:14269"]      
      interval: 30s        
      timeout: 10s         
      retries: 3     
    
    networks:
      - saleor-backend-tier

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8025/api/v1/"]
      interval: 30s        
      timeout: 10s         
      retries: 3          
    
    networks:
      - saleor-backend-tier

volumes:
  saleor-db: 
  saleor-redis:
  saleor-media:
 
networks:
  saleor-backend-tier:
    driver: bridge
