---
name: saleor develop pipeline

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install Dependencies and run Flake
        run: |
          pip install --upgrade pip
          pip install flake8
      
      - name: Run pip-audit (Log Findings, Don’t Fail)
        continue-on-error: true
        run: pip-audit -v || true

      - name: Analyze dependencies for vulnerabilities
        run: pip install pip-audit
      
      - name: Run pip-audit (Log Findings, Don’t Fail)
        continue-on-error: true
        run: pip-audit -v || true

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/develop:develop -f saleor-api/Dockerfile saleor-api/

      - name: Run Health Check (Accept 200 or 404)
        run: |
          docker run -d --name temp_container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/develop:develop
          sleep 10
          if curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/graphql | grep -qE "200|404"; then
            echo "✅ Health Check Passed"
          else
            echo "❌ Health Check Failed" && exit 1
          fi
          docker stop temp_container && docker rm temp_container

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO - https://aquasecurity.github.io/trivy/releases/latest/install.sh | sudo bash          

      - name: Run Trivy Scan
        continue-on-error: true
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/develop:develop


      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/develop:develop
